#!/bin/bash

###############################
# Makes a picture into the file
# wallpaper which is used in
# all of my configuration files
###############################

if [ $# -ne 1 ]
then
	echo "You can make ONE picture your wallpaper!"
else
	cp $1 ~/Pictures/wallpaper
fi
